//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Weather_Aplication.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Weather_Aplication.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _ {
            get {
                object obj = ResourceManager.GetObject("_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _return {
            get {
                object obj = ResourceManager.GetObject("_return", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon app_icon {
            get {
                object obj = ResourceManager.GetObject("app_icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap app_icon1 {
            get {
                object obj = ResourceManager.GetObject("app_icon1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bg_evening {
            get {
                object obj = ResourceManager.GetObject("bg_evening", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bg_morning {
            get {
                object obj = ResourceManager.GetObject("bg_morning", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amsterdam
        ///Ankara
        ///Athens
        ///Belgrade
        ///Berlin
        ///Bratislava
        ///Brussels
        ///Bucharest
        ///Budapest
        ///Copenhagen
        ///Dublin Airport
        ///Helsinki
        ///Kiev
        ///Chisinau
        ///Lisbon
        ///Ljubljana
        ///London
        ///Luxembourg
        ///Madrid
        ///Malta
        ///Minsk
        ///Moscow
        ///Oslo
        ///Paris
        ///Podgorica
        ///Praha-Libus
        ///Pratica Di Mare
        ///Reykjavik
        ///Riga
        ///Sarajevo-Bejelave
        ///Skopje
        ///Sofia
        ///Stockholm
        ///Tallinn
        ///Tirana
        ///Vaduz
        ///Vienna
        ///Vilnius.
        /// </summary>
        internal static string Cities {
            get {
                return ResourceManager.GetString("Cities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap clear_d {
            get {
                object obj = ResourceManager.GetObject("clear_d", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap clear_day {
            get {
                object obj = ResourceManager.GetObject("clear_day", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap clear_n {
            get {
                object obj = ResourceManager.GetObject("clear_n", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap clear_night {
            get {
                object obj = ResourceManager.GetObject("clear_night", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cloudy_d {
            get {
                object obj = ResourceManager.GetObject("cloudy_d", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cloudy_day_night {
            get {
                object obj = ResourceManager.GetObject("cloudy_day_night", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cloudy_n {
            get {
                object obj = ResourceManager.GetObject("cloudy_n", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ds_clear_day {
            get {
                object obj = ResourceManager.GetObject("ds_clear_day", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ds_clear_night {
            get {
                object obj = ResourceManager.GetObject("ds_clear_night", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ds_cloudy_day_night {
            get {
                object obj = ResourceManager.GetObject("ds_cloudy_day_night", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ds_dust_day_night {
            get {
                object obj = ResourceManager.GetObject("ds_dust_day_night", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ds_fair_day {
            get {
                object obj = ResourceManager.GetObject("ds_fair_day", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ds_fair_night {
            get {
                object obj = ResourceManager.GetObject("ds_fair_night", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ds_flurries_day_night {
            get {
                object obj = ResourceManager.GetObject("ds_flurries_day_night", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ds_fog_day_night {
            get {
                object obj = ResourceManager.GetObject("ds_fog_day_night", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ds_fog_moon_night {
            get {
                object obj = ResourceManager.GetObject("ds_fog_moon_night", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ds_fog_sun_day {
            get {
                object obj = ResourceManager.GetObject("ds_fog_sun_day", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ds_freezing_rain_day_night {
            get {
                object obj = ResourceManager.GetObject("ds_freezing_rain_day_night", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ds_hail_day_night {
            get {
                object obj = ResourceManager.GetObject("ds_hail_day_night", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ds_haze_day_night {
            get {
                object obj = ResourceManager.GetObject("ds_haze_day_night", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ds_heavy_rain_day_night {
            get {
                object obj = ResourceManager.GetObject("ds_heavy_rain_day_night", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ds_heavy_snow_day_night {
            get {
                object obj = ResourceManager.GetObject("ds_heavy_snow_day_night", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ds_hurricane_day_night {
            get {
                object obj = ResourceManager.GetObject("ds_hurricane_day_night", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ds_light_rain_day_night {
            get {
                object obj = ResourceManager.GetObject("ds_light_rain_day_night", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ds_mostly_cloudy_day_night {
            get {
                object obj = ResourceManager.GetObject("ds_mostly_cloudy_day_night", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ds_partly_cloudy_day {
            get {
                object obj = ResourceManager.GetObject("ds_partly_cloudy_day", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ds_partly_cloudy_night {
            get {
                object obj = ResourceManager.GetObject("ds_partly_cloudy_night", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ds_rain_day_night {
            get {
                object obj = ResourceManager.GetObject("ds_rain_day_night", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ds_scattered_showers_day_night {
            get {
                object obj = ResourceManager.GetObject("ds_scattered_showers_day_night", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ds_scattered_thundershowers_night {
            get {
                object obj = ResourceManager.GetObject("ds_scattered_thundershowers_night", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ds_scatttered_thundershowers_day {
            get {
                object obj = ResourceManager.GetObject("ds_scatttered_thundershowers_day", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ds_sleet_mix_day_night {
            get {
                object obj = ResourceManager.GetObject("ds_sleet_mix_day_night", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ds_smoky_day_night {
            get {
                object obj = ResourceManager.GetObject("ds_smoky_day_night", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ds_snow_day_night {
            get {
                object obj = ResourceManager.GetObject("ds_snow_day_night", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ds_snow_rain_mix_day_night {
            get {
                object obj = ResourceManager.GetObject("ds_snow_rain_mix_day_night", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ds_thundershowers_day_night {
            get {
                object obj = ResourceManager.GetObject("ds_thundershowers_day_night", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ds_tornado_day_night {
            get {
                object obj = ResourceManager.GetObject("ds_tornado_day_night", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ds_windy_day_night {
            get {
                object obj = ResourceManager.GetObject("ds_windy_day_night", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap dust_day_night {
            get {
                object obj = ResourceManager.GetObject("dust_day_night", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap fair_day {
            get {
                object obj = ResourceManager.GetObject("fair_day", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap fair_night {
            get {
                object obj = ResourceManager.GetObject("fair_night", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap flurries_day_night {
            get {
                object obj = ResourceManager.GetObject("flurries_day_night", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap fog_day_night {
            get {
                object obj = ResourceManager.GetObject("fog_day_night", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap fog_moon_night {
            get {
                object obj = ResourceManager.GetObject("fog_moon_night", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap fog_sun_day {
            get {
                object obj = ResourceManager.GetObject("fog_sun_day", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap foggy_d {
            get {
                object obj = ResourceManager.GetObject("foggy_d", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap foggy_n {
            get {
                object obj = ResourceManager.GetObject("foggy_n", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap freezing_rain_day_night {
            get {
                object obj = ResourceManager.GetObject("freezing_rain_day_night", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 22
        ///44
        ///16.07.2017
        ///Sunday
        ///4:46
        ///19:57
        ///cloudy
        ///22
        ///17
        ///E
        ///7.2
        ///17.07.2017
        ///Monday
        ///4:47
        ///19:56
        ///prevailingly cloudy
        ///24
        ///17
        ///NE
        ///14.4
        ///18.07.2017
        ///Tuesday
        ///4:48
        ///19:56
        ///partly cloudy
        ///28
        ///16
        ///NE
        ///7.2
        ///19.07.2017
        ///Wednesday
        ///4:49
        ///19:55
        ///mostly clear
        ///30
        ///16
        ///N
        ///7.2
        ///.
        /// </summary>
        internal static string Get_Data_For_App {
            get {
                return ResourceManager.GetString("Get_Data_For_App", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 19
        ///88
        ///23.07.2017
        ///Sunday
        ///5:48
        ///21:46
        ///prevailingly cloudy
        ///19
        ///14
        ///SW
        ///14.4
        ///24.07.2017
        ///Monday
        ///5:50
        ///21:44
        ///cloudy
        ///19
        ///14
        ///SE
        ///7.2
        ///25.07.2017
        ///Tuesday
        ///5:51
        ///21:43
        ///prevailingly cloudy
        ///20
        ///15
        ///NW
        ///14.4
        ///26.07.2017
        ///Wednesday
        ///5:53
        ///21:41
        ///cloudy
        ///22
        ///13
        ///SW
        ///14.4
        ///27.07.2017
        ///Thursday
        ///5:54
        ///21:40
        ///prevailingly cloudy
        ///19
        ///16
        ///W
        ///14.4
        ///Amsterdam.
        /// </summary>
        internal static string Get_Data_For_App_Amsterdam {
            get {
                return ResourceManager.GetString("Get_Data_For_App_Amsterdam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 29
        ///47
        ///23.07.2017
        ///Sunday
        ///4:38
        ///19:11
        ///clear
        ///29
        ///14
        ///NE
        ///7.2
        ///24.07.2017
        ///Monday
        ///4:39
        ///19:10
        ///clear
        ///29
        ///16
        ///NE
        ///7.2
        ///25.07.2017
        ///Tuesday
        ///4:40
        ///19:09
        ///clear
        ///32
        ///16
        ///W
        ///7.2
        ///26.07.2017
        ///Wednesday
        ///4:41
        ///19:08
        ///clear
        ///34
        ///18
        ///SW
        ///14.4
        ///27.07.2017
        ///Thursday
        ///4:42
        ///19:07
        ///mostly clear
        ///34
        ///18
        ///SW
        ///14.4
        ///Ankara.
        /// </summary>
        internal static string Get_Data_For_App_Ankara {
            get {
                return ResourceManager.GetString("Get_Data_For_App_Ankara", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 32
        ///39
        ///23.07.2017
        ///Sunday
        ///5:21
        ///19:42
        ///clear
        ///32
        ///24
        ///S
        ///7.2
        ///24.07.2017
        ///Monday
        ///5:22
        ///19:41
        ///clear
        ///32
        ///26
        ///SW
        ///7.2
        ///25.07.2017
        ///Tuesday
        ///5:22
        ///19:40
        ///clear
        ///32
        ///25
        ///S
        ///14.4
        ///26.07.2017
        ///Wednesday
        ///5:23
        ///19:39
        ///clear
        ///31
        ///26
        ///SW
        ///14.4
        ///27.07.2017
        ///Thursday
        ///5:24
        ///19:39
        ///mostly clear
        ///30
        ///24
        ///NW
        ///14.4
        ///Athens.
        /// </summary>
        internal static string Get_Data_For_App_Athens {
            get {
                return ResourceManager.GetString("Get_Data_For_App_Athens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 35
        ///56
        ///23.07.2017
        ///Sunday
        ///5:14
        ///20:14
        ///partly cloudy
        ///35
        ///21
        ///W
        ///14.4
        ///24.07.2017
        ///Monday
        ///5:15
        ///20:13
        ///prevailingly cloudy
        ///35
        ///21
        ///SW
        ///14.4
        ///25.07.2017
        ///Tuesday
        ///5:16
        ///20:12
        ///prevailingly cloudy
        ///25
        ///20
        ///W
        ///14.4
        ///26.07.2017
        ///Wednesday
        ///5:17
        ///20:11
        ///prevailingly cloudy
        ///27
        ///18
        ///NE
        ///7.2
        ///27.07.2017
        ///Thursday
        ///5:19
        ///20:10
        ///partly cloudy
        ///23
        ///16
        ///NW
        ///14.4
        ///Belgrade.
        /// </summary>
        internal static string Get_Data_For_App_Belgrade {
            get {
                return ResourceManager.GetString("Get_Data_For_App_Belgrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 23
        ///95
        ///23.07.2017
        ///Sunday
        ///5:13
        ///21:12
        ///prevailingly cloudy
        ///24
        ///17
        ///W
        ///25.2
        ///24.07.2017
        ///Monday
        ///5:14
        ///21:11
        ///cloudy
        ///23
        ///14
        ///SE
        ///3.6
        ///25.07.2017
        ///Tuesday
        ///5:16
        ///21:09
        ///cloudy
        ///17
        ///15
        ///NW
        ///14.4
        ///26.07.2017
        ///Wednesday
        ///5:17
        ///21:08
        ///cloudy
        ///17
        ///15
        ///W
        ///25.2
        ///27.07.2017
        ///Thursday
        ///5:19
        ///21:06
        ///cloudy
        ///22
        ///15
        ///W
        ///14.4
        ///Berlin.
        /// </summary>
        internal static string Get_Data_For_App_Berlin {
            get {
                return ResourceManager.GetString("Get_Data_For_App_Berlin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 24
        ///83
        ///23.07.2017
        ///Sunday
        ///5:16
        ///20:39
        ///prevailingly cloudy
        ///27
        ///19
        ///NW
        ///14.4
        ///24.07.2017
        ///Monday
        ///5:17
        ///20:38
        ///cloudy
        ///27
        ///20
        ///S
        ///14.4
        ///25.07.2017
        ///Tuesday
        ///5:18
        ///20:37
        ///cloudy
        ///24
        ///18
        ///NW
        ///25.2
        ///26.07.2017
        ///Wednesday
        ///5:19
        ///20:35
        ///prevailingly cloudy
        ///22
        ///15
        ///W
        ///25.2
        ///27.07.2017
        ///Thursday
        ///5:20
        ///20:34
        ///cloudy
        ///22
        ///14
        ///NW
        ///14.4
        ///Bratislava.
        /// </summary>
        internal static string Get_Data_For_App_Bratislava {
            get {
                return ResourceManager.GetString("Get_Data_For_App_Bratislava", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 32
        ///73
        ///23.07.2017
        ///Sunday
        ///4:53
        ///19:51
        ///partly cloudy
        ///32
        ///22
        ///NE
        ///3.6
        ///24.07.2017
        ///Monday
        ///4:54
        ///19:50
        ///partly cloudy
        ///32
        ///21
        ///SE
        ///3.6
        ///25.07.2017
        ///Tuesday
        ///4:55
        ///19:49
        ///prevailingly cloudy
        ///33
        ///21
        ///SE
        ///14.4
        ///26.07.2017
        ///Wednesday
        ///4:56
        ///19:48
        ///mostly clear
        ///30
        ///19
        ///W
        ///14.4
        ///27.07.2017
        ///Thursday
        ///4:57
        ///19:47
        ///cloudy
        ///23
        ///19
        ///NE
        ///3.6
        ///Brussels.
        /// </summary>
        internal static string Get_Data_For_App_Brussels {
            get {
                return ResourceManager.GetString("Get_Data_For_App_Brussels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 29
        ///74
        ///23.07.2017
        ///Sunday
        ///5:10
        ///20:28
        ///prevailingly cloudy
        ///31
        ///20
        ///N
        ///7.2
        ///24.07.2017
        ///Monday
        ///5:12
        ///20:27
        ///prevailingly cloudy
        ///31
        ///20
        ///S
        ///7.2
        ///25.07.2017
        ///Tuesday
        ///5:13
        ///20:26
        ///prevailingly cloudy
        ///25
        ///18
        ///NW
        ///25.2
        ///26.07.2017
        ///Wednesday
        ///5:14
        ///20:25
        ///partly cloudy
        ///25
        ///16
        ///W
        ///14.4
        ///27.07.2017
        ///Thursday
        ///5:15
        ///20:24
        ///prevailingly cloudy
        ///22
        ///16
        ///NW
        ///14.4
        ///Bucharest.
        /// </summary>
        internal static string Get_Data_For_App_Bucharest {
            get {
                return ResourceManager.GetString("Get_Data_For_App_Bucharest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 18
        ///77
        ///23.07.2017
        ///Sunday
        ///5:00
        ///21:31
        ///cloudy
        ///18
        ///16
        ///E
        ///25.2
        ///24.07.2017
        ///Monday
        ///5:01
        ///21:29
        ///prevailingly cloudy
        ///18
        ///14
        ///S
        ///7.2
        ///25.07.2017
        ///Tuesday
        ///5:03
        ///21:28
        ///cloudy
        ///19
        ///15
        ///N
        ///25.2
        ///26.07.2017
        ///Wednesday
        ///5:05
        ///21:26
        ///cloudy
        ///17
        ///16
        ///N
        ///25.2
        ///27.07.2017
        ///Thursday
        ///5:06
        ///21:24
        ///cloudy
        ///19
        ///16
        ///NW
        ///14.4
        ///Budapest.
        /// </summary>
        internal static string Get_Data_For_App_Budapest {
            get {
                return ResourceManager.GetString("Get_Data_For_App_Budapest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 24
        ///81
        ///23.07.2017
        ///Sunday
        ///7:30
        ///21:55
        ///clear
        ///26
        ///18
        ///N
        ///32.4
        ///24.07.2017
        ///Monday
        ///7:31
        ///21:55
        ///clear
        ///25
        ///18
        ///N
        ///25.2
        ///25.07.2017
        ///Tuesday
        ///7:32
        ///21:54
        ///clear
        ///29
        ///18
        ///N
        ///25.2
        ///26.07.2017
        ///Wednesday
        ///7:33
        ///21:53
        ///clear
        ///28
        ///19
        ///N
        ///25.2
        ///27.07.2017
        ///Thursday
        ///7:34
        ///21:52
        ///clear
        ///29
        ///19
        ///N
        ///25.2
        ///Chisinau.
        /// </summary>
        internal static string Get_Data_For_App_Chisinau {
            get {
                return ResourceManager.GetString("Get_Data_For_App_Chisinau", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 18
        ///92
        ///23.07.2017
        ///Sunday
        ///6:27
        ///22:35
        ///cloudy
        ///20
        ///13
        ///NE
        ///14.4
        ///24.07.2017
        ///Monday
        ///6:28
        ///22:34
        ///prevailingly cloudy
        ///23
        ///13
        ///NW
        ///14.4
        ///25.07.2017
        ///Tuesday
        ///6:30
        ///22:32
        ///partly cloudy
        ///21
        ///12
        ///S
        ///0.7200000000000001
        ///26.07.2017
        ///Wednesday
        ///6:31
        ///22:31
        ///cloudy
        ///18
        ///16
        ///W
        ///25.2
        ///27.07.2017
        ///Thursday
        ///6:33
        ///22:29
        ///prevailingly cloudy
        ///17
        ///13
        ///SW
        ///25.2
        ///Copenhagen.
        /// </summary>
        internal static string Get_Data_For_App_Copenhagen {
            get {
                return ResourceManager.GetString("Get_Data_For_App_Copenhagen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 21
        ///71
        ///23.07.2017
        ///Sunday
        ///3:38
        ///21:14
        ///partly cloudy
        ///21
        ///9
        ///NW
        ///7.2
        ///24.07.2017
        ///Monday
        ///3:40
        ///21:12
        ///prevailingly cloudy
        ///18
        ///11
        ///N
        ///7.2
        ///25.07.2017
        ///Tuesday
        ///3:42
        ///21:09
        ///prevailingly cloudy
        ///21
        ///12
        ///NE
        ///3.6
        ///26.07.2017
        ///Wednesday
        ///3:45
        ///21:07
        ///prevailingly cloudy
        ///21
        ///14
        ///E
        ///7.2
        ///27.07.2017
        ///Thursday
        ///3:47
        ///21:05
        ///clear
        ///24
        ///14
        ///E
        ///14.4
        ///Dublin Airport.
        /// </summary>
        internal static string Get_Data_For_App_Dublin_Airport {
            get {
                return ResourceManager.GetString("Get_Data_For_App_Dublin_Airport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 26
        ///67
        ///23.07.2017
        ///Sunday
        ///4:13
        ///19:54
        ///mostly clear
        ///26
        ///16
        ///N
        ///7.2
        ///24.07.2017
        ///Monday
        ///4:15
        ///19:53
        ///prevailingly cloudy
        ///27
        ///15
        ///SE
        ///7.2
        ///25.07.2017
        ///Tuesday
        ///4:16
        ///19:52
        ///partly cloudy
        ///30
        ///19
        ///SE
        ///25.2
        ///26.07.2017
        ///Wednesday
        ///4:17
        ///19:50
        ///partly cloudy
        ///30
        ///20
        ///S
        ///25.2
        ///27.07.2017
        ///Thursday
        ///4:19
        ///19:49
        ///prevailingly cloudy
        ///28
        ///18
        ///N
        ///7.2
        ///Helsinki.
        /// </summary>
        internal static string Get_Data_For_App_Helsinki {
            get {
                return ResourceManager.GetString("Get_Data_For_App_Helsinki", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 30
        ///60
        ///23.07.2017
        ///Sunday
        ///4:33
        ///19:48
        ///mostly clear
        ///31
        ///20
        ///NW
        ///7.2
        ///24.07.2017
        ///Monday
        ///4:34
        ///19:47
        ///prevailingly cloudy
        ///32
        ///21
        ///SE
        ///7.2
        ///25.07.2017
        ///Tuesday
        ///4:35
        ///19:46
        ///partly cloudy
        ///32
        ///20
        ///S
        ///14.4
        ///26.07.2017
        ///Wednesday
        ///4:36
        ///19:44
        ///prevailingly cloudy
        ///28
        ///19
        ///SW
        ///7.2
        ///27.07.2017
        ///Thursday
        ///4:37
        ///19:43
        ///cloudy
        ///26
        ///19
        ///NE
        ///7.2
        ///Kiev.
        /// </summary>
        internal static string Get_Data_For_App_Kiev {
            get {
                return ResourceManager.GetString("Get_Data_For_App_Kiev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 30
        ///50
        ///23.07.2017
        ///Sunday
        ///5:34
        ///20:42
        ///partly cloudy
        ///32
        ///18
        ///W
        ///7.2
        ///24.07.2017
        ///Monday
        ///5:35
        ///20:41
        ///cloudy
        ///23
        ///18
        ///SW
        ///7.2
        ///25.07.2017
        ///Tuesday
        ///5:36
        ///20:40
        ///prevailingly cloudy
        ///24
        ///16
        ///NE
        ///3.6
        ///26.07.2017
        ///Wednesday
        ///5:37
        ///20:39
        ///prevailingly cloudy
        ///22
        ///13
        ///NW
        ///3.6
        ///27.07.2017
        ///Thursday
        ///5:38
        ///20:38
        ///prevailingly cloudy
        ///25
        ///12
        ///N
        ///3.6
        ///Lisbon.
        /// </summary>
        internal static string Get_Data_For_App_Lisbon {
            get {
                return ResourceManager.GetString("Get_Data_For_App_Lisbon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 15
        ///99
        ///23.07.2017
        ///Sunday
        ///6:13
        ///22:03
        ///prevailingly cloudy
        ///18
        ///11
        ///SW
        ///14.4
        ///24.07.2017
        ///Monday
        ///6:14
        ///22:02
        ///cloudy
        ///20
        ///13
        ///N
        ///25.2
        ///25.07.2017
        ///Tuesday
        ///6:16
        ///22:00
        ///prevailingly cloudy
        ///22
        ///14
        ///N
        ///14.4
        ///26.07.2017
        ///Wednesday
        ///6:17
        ///21:59
        ///cloudy
        ///20
        ///14
        ///S
        ///25.2
        ///27.07.2017
        ///Thursday
        ///6:18
        ///21:57
        ///cloudy
        ///19
        ///12
        ///W
        ///25.2
        ///Ljubljana.
        /// </summary>
        internal static string Get_Data_For_App_Ljubljana {
            get {
                return ResourceManager.GetString("Get_Data_For_App_Ljubljana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 19
        ///94
        ///23.07.2017
        ///Sunday
        ///5:54
        ///21:29
        ///prevailingly cloudy
        ///20
        ///14
        ///SW
        ///25.2
        ///24.07.2017
        ///Monday
        ///5:55
        ///21:27
        ///prevailingly cloudy
        ///18
        ///13
        ///W
        ///14.4
        ///25.07.2017
        ///Tuesday
        ///5:57
        ///21:26
        ///cloudy
        ///17
        ///12
        ///NW
        ///25.2
        ///26.07.2017
        ///Wednesday
        ///5:58
        ///21:25
        ///cloudy
        ///20
        ///12
        ///W
        ///14.4
        ///27.07.2017
        ///Thursday
        ///5:59
        ///21:23
        ///cloudy
        ///19
        ///16
        ///W
        ///25.2
        ///London.
        /// </summary>
        internal static string Get_Data_For_App_London {
            get {
                return ResourceManager.GetString("Get_Data_For_App_London", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 33
        ///60
        ///23.07.2017
        ///Sunday
        ///7:03
        ///21:38
        ///clear
        ///34
        ///18
        ///SW
        ///14.4
        ///24.07.2017
        ///Monday
        ///7:04
        ///21:37
        ///clear
        ///33
        ///19
        ///N
        ///7.2
        ///25.07.2017
        ///Tuesday
        ///7:05
        ///21:36
        ///partly cloudy
        ///32
        ///17
        ///NE
        ///7.2
        ///26.07.2017
        ///Wednesday
        ///7:06
        ///21:35
        ///clear
        ///34
        ///17
        ///NW
        ///0.7200000000000001
        ///27.07.2017
        ///Thursday
        ///7:07
        ///21:34
        ///clear
        ///37
        ///20
        ///SW
        ///7.2
        ///Luxembourg.
        /// </summary>
        internal static string Get_Data_For_App_Luxembourg {
            get {
                return ResourceManager.GetString("Get_Data_For_App_Luxembourg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 30
        ///71
        ///23.07.2017
        ///Sunday
        ///6:03
        ///20:14
        ///clear
        ///30
        ///26
        ///SW
        ///14.4
        ///24.07.2017
        ///Monday
        ///6:04
        ///20:13
        ///partly cloudy
        ///31
        ///25
        ///SW
        ///7.2
        ///25.07.2017
        ///Tuesday
        ///6:04
        ///20:12
        ///clear
        ///28
        ///26
        ///NW
        ///32.4
        ///26.07.2017
        ///Wednesday
        ///6:05
        ///20:12
        ///mostly clear
        ///27
        ///24
        ///NW
        ///32.4
        ///27.07.2017
        ///Thursday
        ///6:06
        ///20:11
        ///mostly clear
        ///26
        ///24
        ///NW
        ///32.4
        ///Madrid.
        /// </summary>
        internal static string Get_Data_For_App_Madrid {
            get {
                return ResourceManager.GetString("Get_Data_For_App_Madrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 22
        ///50
        ///23.07.2017
        ///Sunday
        ///4:09
        ///20:22
        ///prevailingly cloudy
        ///22
        ///12
        ///N
        ///3.6
        ///24.07.2017
        ///Monday
        ///4:10
        ///20:21
        ///prevailingly cloudy
        ///22
        ///14
        ///S
        ///14.4
        ///25.07.2017
        ///Tuesday
        ///4:12
        ///20:19
        ///cloudy
        ///26
        ///14
        ///SE
        ///14.4
        ///26.07.2017
        ///Wednesday
        ///4:13
        ///20:18
        ///cloudy
        ///23
        ///18
        ///S
        ///7.2
        ///27.07.2017
        ///Thursday
        ///4:15
        ///20:16
        ///partly cloudy
        ///23
        ///16
        ///SW
        ///14.4
        ///Malta.
        /// </summary>
        internal static string Get_Data_For_App_Malta {
            get {
                return ResourceManager.GetString("Get_Data_For_App_Malta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 20
        ///76
        ///23.07.2017
        ///Sunday
        ///3:17
        ///19:51
        ///mostly clear
        ///20
        ///12
        ///NW
        ///25.2
        ///24.07.2017
        ///Monday
        ///3:19
        ///19:49
        ///prevailingly cloudy
        ///20
        ///12
        ///W
        ///14.4
        ///25.07.2017
        ///Tuesday
        ///3:21
        ///19:47
        ///prevailingly cloudy
        ///21
        ///12
        ///W
        ///3.6
        ///26.07.2017
        ///Wednesday
        ///3:23
        ///19:46
        ///prevailingly cloudy
        ///25
        ///15
        ///SE
        ///7.2
        ///27.07.2017
        ///Thursday
        ///3:24
        ///19:44
        ///cloudy
        ///25
        ///16
        ///SE
        ///7.2
        ///Minsk.
        /// </summary>
        internal static string Get_Data_For_App_Minsk {
            get {
                return ResourceManager.GetString("Get_Data_For_App_Minsk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 23
        ///81
        ///23.07.2017
        ///Sunday
        ///4:34
        ///22:08
        ///prevailingly cloudy
        ///24
        ///12
        ///SW
        ///3.6
        ///24.07.2017
        ///Monday
        ///4:37
        ///22:06
        ///cloudy
        ///18
        ///12
        ///N
        ///7.2
        ///25.07.2017
        ///Tuesday
        ///4:39
        ///22:04
        ///cloudy
        ///20
        ///12
        ///NE
        ///14.4
        ///26.07.2017
        ///Wednesday
        ///4:41
        ///22:02
        ///cloudy
        ///19
        ///13
        ///E
        ///7.2
        ///27.07.2017
        ///Thursday
        ///4:43
        ///21:59
        ///cloudy
        ///15
        ///13
        ///E
        ///3.6
        ///Moscow.
        /// </summary>
        internal static string Get_Data_For_App_Moscow {
            get {
                return ResourceManager.GetString("Get_Data_For_App_Moscow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 21
        ///78
        ///23.07.2017
        ///Sunday
        ///6:13
        ///21:40
        ///cloudy
        ///22
        ///14
        ///SW
        ///25.2
        ///24.07.2017
        ///Monday
        ///6:14
        ///21:39
        ///prevailingly cloudy
        ///20
        ///12
        ///W
        ///25.2
        ///25.07.2017
        ///Tuesday
        ///6:15
        ///21:38
        ///partly cloudy
        ///23
        ///15
        ///NW
        ///25.2
        ///26.07.2017
        ///Wednesday
        ///6:17
        ///21:37
        ///cloudy
        ///24
        ///12
        ///SW
        ///14.4
        ///27.07.2017
        ///Thursday
        ///6:18
        ///21:35
        ///cloudy
        ///23
        ///16
        ///W
        ///14.4
        ///Oslo.
        /// </summary>
        internal static string Get_Data_For_App_Oslo {
            get {
                return ResourceManager.GetString("Get_Data_For_App_Oslo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 35
        ///37
        ///23.07.2017
        ///Sunday
        ///5:26
        ///20:12
        ///mostly clear
        ///36
        ///22
        ///S
        ///7.2
        ///24.07.2017
        ///Monday
        ///5:27
        ///20:11
        ///mostly clear
        ///36
        ///22
        ///S
        ///7.2
        ///25.07.2017
        ///Tuesday
        ///5:28
        ///20:10
        ///prevailingly cloudy
        ///25
        ///18
        ///SE
        ///3.6
        ///26.07.2017
        ///Wednesday
        ///5:29
        ///20:09
        ///prevailingly cloudy
        ///24
        ///19
        ///N
        ///0.7200000000000001
        ///27.07.2017
        ///Thursday
        ///5:30
        ///20:08
        ///partly cloudy
        ///26
        ///16
        ///NW
        ///3.6
        ///Paris.
        /// </summary>
        internal static string Get_Data_For_App_Paris {
            get {
                return ResourceManager.GetString("Get_Data_For_App_Paris", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 26
        ///84
        ///23.07.2017
        ///Sunday
        ///5:19
        ///20:57
        ///prevailingly cloudy
        ///26
        ///16
        ///W
        ///14.4
        ///24.07.2017
        ///Monday
        ///5:21
        ///20:56
        ///cloudy
        ///21
        ///15
        ///NE
        ///3.6
        ///25.07.2017
        ///Tuesday
        ///5:22
        ///20:55
        ///cloudy
        ///21
        ///14
        ///W
        ///14.4
        ///26.07.2017
        ///Wednesday
        ///5:23
        ///20:53
        ///cloudy
        ///16
        ///12
        ///W
        ///25.2
        ///27.07.2017
        ///Thursday
        ///5:25
        ///20:52
        ///cloudy
        ///20
        ///14
        ///W
        ///25.2
        ///Podgorica.
        /// </summary>
        internal static string Get_Data_For_App_Podgorica {
            get {
                return ResourceManager.GetString("Get_Data_For_App_Podgorica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 28
        ///72
        ///23.07.2017
        ///Sunday
        ///5:56
        ///20:37
        ///clear
        ///28
        ///23
        ///W
        ///14.4
        ///24.07.2017
        ///Monday
        ///5:57
        ///20:36
        ///mostly clear
        ///27
        ///23
        ///SW
        ///25.2
        ///25.07.2017
        ///Tuesday
        ///5:58
        ///20:35
        ///clear
        ///27
        ///23
        ///W
        ///25.2
        ///26.07.2017
        ///Wednesday
        ///5:59
        ///20:34
        ///mostly clear
        ///27
        ///21
        ///SW
        ///14.4
        ///27.07.2017
        ///Thursday
        ///6:00
        ///20:33
        ///clear
        ///27
        ///22
        ///W
        ///25.2
        ///Praha-Libus.
        /// </summary>
        internal static string Get_Data_For_App_Praha_Libus {
            get {
                return ResourceManager.GetString("Get_Data_For_App_Praha_Libus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 13
        ///77
        ///23.07.2017
        ///Sunday
        ///6:06
        ///0:59
        ///prevailingly cloudy
        ///14
        ///11
        ///SE
        ///25.2
        ///24.07.2017
        ///Monday
        ///6:09
        ///0:56
        ///cloudy
        ///15
        ///12
        ///SE
        ///14.4
        ///25.07.2017
        ///Tuesday
        ///6:13
        ///0:53
        ///cloudy
        ///15
        ///11
        ///SE
        ///25.2
        ///26.07.2017
        ///Wednesday
        ///6:16
        ///0:50
        ///mostly clear
        ///20
        ///11
        ///NE
        ///7.2
        ///27.07.2017
        ///Thursday
        ///6:19
        ///0:47
        ///prevailingly cloudy
        ///19
        ///9
        ///NW
        ///3.6
        ///Pratica Di Mare.
        /// </summary>
        internal static string Get_Data_For_App_Pratica_Di_Mare {
            get {
                return ResourceManager.GetString("Get_Data_For_App_Pratica_Di_Mare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 20
        ///63
        ///23.07.2017
        ///Sunday
        ///4:06
        ///20:54
        ///prevailingly cloudy
        ///21
        ///10
        ///N
        ///14.4
        ///24.07.2017
        ///Monday
        ///4:08
        ///20:52
        ///cloudy
        ///19
        ///13
        ///E
        ///14.4
        ///25.07.2017
        ///Tuesday
        ///4:09
        ///20:50
        ///cloudy
        ///23
        ///13
        ///NE
        ///14.4
        ///26.07.2017
        ///Wednesday
        ///4:11
        ///20:48
        ///cloudy
        ///23
        ///16
        ///E
        ///14.4
        ///27.07.2017
        ///Thursday
        ///4:13
        ///20:46
        ///cloudy
        ///21
        ///18
        ///SE
        ///7.2
        ///Reykjavik.
        /// </summary>
        internal static string Get_Data_For_App_Reykjavik {
            get {
                return ResourceManager.GetString("Get_Data_For_App_Reykjavik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 28
        ///68
        ///23.07.2017
        ///Sunday
        ///5:25
        ///20:20
        ///mostly clear
        ///28
        ///17
        ///W
        ///7.2
        ///24.07.2017
        ///Monday
        ///5:26
        ///20:19
        ///partly cloudy
        ///27
        ///17
        ///S
        ///7.2
        ///25.07.2017
        ///Tuesday
        ///5:27
        ///20:18
        ///prevailingly cloudy
        ///21
        ///14
        ///NW
        ///7.2
        ///26.07.2017
        ///Wednesday
        ///5:28
        ///20:17
        ///partly cloudy
        ///18
        ///12
        ///W
        ///3.6
        ///27.07.2017
        ///Thursday
        ///5:30
        ///20:15
        ///prevailingly cloudy
        ///18
        ///11
        ///NW
        ///7.2
        ///Riga.
        /// </summary>
        internal static string Get_Data_For_App_Riga {
            get {
                return ResourceManager.GetString("Get_Data_For_App_Riga", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 38
        ///56
        ///23.07.2017
        ///Sunday
        ///5:18
        ///20:01
        ///partly cloudy
        ///38
        ///22
        ///W
        ///3.6
        ///24.07.2017
        ///Monday
        ///5:19
        ///20:00
        ///mostly clear
        ///38
        ///24
        ///S
        ///7.2
        ///25.07.2017
        ///Tuesday
        ///5:20
        ///19:59
        ///mostly clear
        ///34
        ///22
        ///W
        ///7.2
        ///26.07.2017
        ///Wednesday
        ///5:21
        ///19:58
        ///partly cloudy
        ///31
        ///20
        ///W
        ///0.7200000000000001
        ///27.07.2017
        ///Thursday
        ///5:22
        ///19:57
        ///partly cloudy
        ///28
        ///18
        ///N
        ///14.4
        ///Sarajevo-Bejelave.
        /// </summary>
        internal static string Get_Data_For_App_Sarajevo_Bejelave {
            get {
                return ResourceManager.GetString("Get_Data_For_App_Sarajevo_Bejelave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 29
        ///66
        ///23.07.2017
        ///Sunday
        ///5:09
        ///19:56
        ///mostly clear
        ///29
        ///20
        ///E
        ///3.6
        ///24.07.2017
        ///Monday
        ///5:10
        ///19:55
        ///mostly clear
        ///29
        ///20
        ///E
        ///3.6
        ///25.07.2017
        ///Tuesday
        ///5:11
        ///19:54
        ///partly cloudy
        ///27
        ///18
        ///SW
        ///7.2
        ///26.07.2017
        ///Wednesday
        ///5:12
        ///19:53
        ///partly cloudy
        ///24
        ///16
        ///N
        ///3.6
        ///27.07.2017
        ///Thursday
        ///5:13
        ///19:52
        ///partly cloudy
        ///22
        ///14
        ///NW
        ///14.4
        ///Skopje.
        /// </summary>
        internal static string Get_Data_For_App_Skopje {
            get {
                return ResourceManager.GetString("Get_Data_For_App_Skopje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 20
        ///73
        ///23.07.2017
        ///Sunday
        ///4:14
        ///21:35
        ///prevailingly cloudy
        ///21
        ///12
        ///E
        ///7.2
        ///24.07.2017
        ///Monday
        ///4:16
        ///21:32
        ///prevailingly cloudy
        ///22
        ///10
        ///E
        ///7.2
        ///25.07.2017
        ///Tuesday
        ///4:18
        ///21:30
        ///prevailingly cloudy
        ///20
        ///12
        ///E
        ///14.4
        ///26.07.2017
        ///Wednesday
        ///4:20
        ///21:28
        ///cloudy
        ///20
        ///12
        ///E
        ///14.4
        ///27.07.2017
        ///Thursday
        ///4:22
        ///21:26
        ///prevailingly cloudy
        ///24
        ///12
        ///E
        ///14.4
        ///Sofia.
        /// </summary>
        internal static string Get_Data_For_App_Sofia {
            get {
                return ResourceManager.GetString("Get_Data_For_App_Sofia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 20
        ///78
        ///23.07.2017
        ///Sunday
        ///3:49
        ///21:08
        ///mostly clear
        ///20
        ///10
        ///NW
        ///7.2
        ///24.07.2017
        ///Monday
        ///3:51
        ///21:06
        ///partly cloudy
        ///21
        ///10
        ///N
        ///7.2
        ///25.07.2017
        ///Tuesday
        ///3:53
        ///21:04
        ///partly cloudy
        ///20
        ///13
        ///NE
        ///14.4
        ///26.07.2017
        ///Wednesday
        ///3:55
        ///21:01
        ///clear
        ///22
        ///12
        ///NE
        ///14.4
        ///27.07.2017
        ///Thursday
        ///3:57
        ///20:59
        ///mostly clear
        ///25
        ///14
        ///NE
        ///14.4
        ///Stockholm.
        /// </summary>
        internal static string Get_Data_For_App_Stockholm {
            get {
                return ResourceManager.GetString("Get_Data_For_App_Stockholm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 34
        ///48
        ///23.07.2017
        ///Sunday
        ///5:28
        ///20:07
        ///clear
        ///34
        ///23
        ///SW
        ///14.4
        ///24.07.2017
        ///Monday
        ///5:28
        ///20:06
        ///clear
        ///35
        ///21
        ///W
        ///14.4
        ///25.07.2017
        ///Tuesday
        ///5:29
        ///20:05
        ///clear
        ///29
        ///23
        ///SW
        ///14.4
        ///26.07.2017
        ///Wednesday
        ///5:30
        ///20:04
        ///partly cloudy
        ///26
        ///20
        ///W
        ///7.2
        ///27.07.2017
        ///Thursday
        ///5:31
        ///20:03
        ///mostly clear
        ///25
        ///17
        ///NW
        ///14.4
        ///Tallinn.
        /// </summary>
        internal static string Get_Data_For_App_Tallinn {
            get {
                return ResourceManager.GetString("Get_Data_For_App_Tallinn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 18
        ///83
        ///23.07.2017
        ///Sunday
        ///5:50
        ///21:06
        ///cloudy
        ///18
        ///14
        ///N
        ///3.6
        ///24.07.2017
        ///Monday
        ///5:51
        ///21:05
        ///prevailingly cloudy
        ///16
        ///12
        ///N
        ///3.6
        ///25.07.2017
        ///Tuesday
        ///5:53
        ///21:04
        ///cloudy
        ///14
        ///9
        ///W
        ///3.6
        ///26.07.2017
        ///Wednesday
        ///5:54
        ///21:03
        ///cloudy
        ///13
        ///9
        ///W
        ///0.7200000000000001
        ///27.07.2017
        ///Thursday
        ///5:55
        ///21:01
        ///cloudy
        ///16
        ///8
        ///N
        ///3.6
        ///Tirana.
        /// </summary>
        internal static string Get_Data_For_App_Tirana {
            get {
                return ResourceManager.GetString("Get_Data_For_App_Tirana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 26
        ///73
        ///23.07.2017
        ///Sunday
        ///5:19
        ///20:43
        ///prevailingly cloudy
        ///28
        ///19
        ///NW
        ///14.4
        ///24.07.2017
        ///Monday
        ///5:20
        ///20:42
        ///cloudy
        ///26
        ///19
        ///SE
        ///14.4
        ///25.07.2017
        ///Tuesday
        ///5:21
        ///20:40
        ///prevailingly cloudy
        ///23
        ///16
        ///NW
        ///25.2
        ///26.07.2017
        ///Wednesday
        ///5:22
        ///20:39
        ///prevailingly cloudy
        ///21
        ///15
        ///W
        ///32.4
        ///27.07.2017
        ///Thursday
        ///5:24
        ///20:38
        ///cloudy
        ///21
        ///14
        ///NW
        ///14.4
        ///Vaduz.
        /// </summary>
        internal static string Get_Data_For_App_Vaduz {
            get {
                return ResourceManager.GetString("Get_Data_For_App_Vaduz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 22
        ///72
        ///23.07.2017
        ///Sunday
        ///4:15
        ///20:36
        ///cloudy
        ///22
        ///14
        ///SE
        ///7.2
        ///24.07.2017
        ///Monday
        ///4:17
        ///20:34
        ///prevailingly cloudy
        ///23
        ///16
        ///SW
        ///7.2
        ///25.07.2017
        ///Tuesday
        ///4:18
        ///20:33
        ///cloudy
        ///24
        ///14
        ///E
        ///14.4
        ///26.07.2017
        ///Wednesday
        ///4:20
        ///20:31
        ///cloudy
        ///23
        ///18
        ///W
        ///3.6
        ///27.07.2017
        ///Thursday
        ///4:22
        ///20:29
        ///prevailingly cloudy
        ///22
        ///17
        ///SW
        ///14.4
        ///Vienna.
        /// </summary>
        internal static string Get_Data_For_App_Vienna {
            get {
                return ResourceManager.GetString("Get_Data_For_App_Vienna", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 26
        ///89
        ///23.07.2017
        ///Sunday
        ///4:44
        ///20:40
        ///prevailingly cloudy
        ///27
        ///17
        ///S
        ///14.4
        ///24.07.2017
        ///Monday
        ///4:45
        ///20:39
        ///partly cloudy
        ///26
        ///17
        ///NW
        ///7.2
        ///25.07.2017
        ///Tuesday
        ///4:47
        ///20:38
        ///cloudy
        ///24
        ///16
        ///SE
        ///7.2
        ///26.07.2017
        ///Wednesday
        ///4:48
        ///20:36
        ///cloudy
        ///22
        ///14
        ///SW
        ///14.4
        ///27.07.2017
        ///Thursday
        ///4:50
        ///20:35
        ///cloudy
        ///18
        ///15
        ///SW
        ///14.4
        ///Vilnius.
        /// </summary>
        internal static string Get_Data_For_App_Vilnius {
            get {
                return ResourceManager.GetString("Get_Data_For_App_Vilnius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap hail_day_night {
            get {
                object obj = ResourceManager.GetObject("hail_day_night", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap haze_day_night {
            get {
                object obj = ResourceManager.GetObject("haze_day_night", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap heavy_rain_day_night {
            get {
                object obj = ResourceManager.GetObject("heavy_rain_day_night", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap heavy_snow_day_night {
            get {
                object obj = ResourceManager.GetObject("heavy_snow_day_night", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap hurricane_day_night {
            get {
                object obj = ResourceManager.GetObject("hurricane_day_night", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap i {
            get {
                object obj = ResourceManager.GetObject("i", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap onboarding_partlycloudy {
            get {
                object obj = ResourceManager.GetObject("onboarding_partlycloudy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap onboarding_rain {
            get {
                object obj = ResourceManager.GetObject("onboarding_rain", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap partly_cloudy_day {
            get {
                object obj = ResourceManager.GetObject("partly_cloudy_day", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rain_d {
            get {
                object obj = ResourceManager.GetObject("rain_d", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rain_day_night {
            get {
                object obj = ResourceManager.GetObject("rain_day_night", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rain_ico_0 {
            get {
                object obj = ResourceManager.GetObject("rain_ico_0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rain_ico_10 {
            get {
                object obj = ResourceManager.GetObject("rain_ico_10", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rain_ico_100 {
            get {
                object obj = ResourceManager.GetObject("rain_ico_100", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rain_ico_20 {
            get {
                object obj = ResourceManager.GetObject("rain_ico_20", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rain_ico_30 {
            get {
                object obj = ResourceManager.GetObject("rain_ico_30", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rain_ico_40 {
            get {
                object obj = ResourceManager.GetObject("rain_ico_40", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rain_ico_50 {
            get {
                object obj = ResourceManager.GetObject("rain_ico_50", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rain_ico_60 {
            get {
                object obj = ResourceManager.GetObject("rain_ico_60", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rain_ico_70 {
            get {
                object obj = ResourceManager.GetObject("rain_ico_70", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rain_ico_80 {
            get {
                object obj = ResourceManager.GetObject("rain_ico_80", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rain_ico_90 {
            get {
                object obj = ResourceManager.GetObject("rain_ico_90", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rain_n {
            get {
                object obj = ResourceManager.GetObject("rain_n", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap scattered_showers_day_night {
            get {
                object obj = ResourceManager.GetObject("scattered_showers_day_night", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap scattered_thunderstorms_night {
            get {
                object obj = ResourceManager.GetObject("scattered_thunderstorms_night", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap scatttered_thundershowers_day {
            get {
                object obj = ResourceManager.GetObject("scatttered_thundershowers_day", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap search {
            get {
                object obj = ResourceManager.GetObject("search", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap sleet_day_night {
            get {
                object obj = ResourceManager.GetObject("sleet_day_night", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap sleet_mix_day_night {
            get {
                object obj = ResourceManager.GetObject("sleet_mix_day_night", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap smoky_day_night {
            get {
                object obj = ResourceManager.GetObject("smoky_day_night", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap snow_d {
            get {
                object obj = ResourceManager.GetObject("snow_d", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap snow_day_night {
            get {
                object obj = ResourceManager.GetObject("snow_day_night", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap snow_n {
            get {
                object obj = ResourceManager.GetObject("snow_n", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap snow_rain_mix_day_night {
            get {
                object obj = ResourceManager.GetObject("snow_rain_mix_day_night", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap storm_d {
            get {
                object obj = ResourceManager.GetObject("storm_d", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap storm_n {
            get {
                object obj = ResourceManager.GetObject("storm_n", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap thundershowers_day_night {
            get {
                object obj = ResourceManager.GetObject("thundershowers_day_night", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap thunderstorm_day_night {
            get {
                object obj = ResourceManager.GetObject("thunderstorm_day_night", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap tornado_day_night {
            get {
                object obj = ResourceManager.GetObject("tornado_day_night", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap windowicons {
            get {
                object obj = ResourceManager.GetObject("windowicons", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap x {
            get {
                object obj = ResourceManager.GetObject("x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
